[Postgresql]
host = "120.78.76.139"
port= "5432"
username = "mapPlatform"
password = "mapPlatform"
dbname="mp2"

[JWT]
# 下列值设为0或者不填则为默认值
# JWT过期时间 默认6小时=21600秒 
# expiredtime = 21600
# hmacSampleSecret 设置过期和解密字符串时间 默认:mapPlatformtokenhmacSampleSecret
# hmacSampleSecret = "mapPlatformtokenhmacSampleSecret"

[Server]
port= ":8800"
ip="192.168.181.60"

[Admin]
name="admin"
password="admin"

[Redis]
# redis url like : url="redis://localhost:6379"
url="redis://localhost:6379"
# Whether to clear the redis cache: true is yes, false is no
clearUp = true
# Maximum number of idle connections in the pool.
maxIdle = 30