version: '2.0'
services:
  mymapp_app:
    image: alpine:latest
    ports:
      - 8800:8800
      - 8801:8801
    depends_on:
      - mymapp_sql
      - mymapp_redis
    volumes:
      - $PWD:/mymapp
    working_dir: /mymapp
    command: ./mymapp
    restart: always

  mymapp_sql:
    image: postgres:latest
    ports:
      - 8802:5432
    environment:
      - POSTGRES_PASSWORD=mapPlatform
      - POSTGRES_USER=mapPlatform
      - POSTGRES_DB=mp2
    volumes:
      - ./postgresqldb/:/var/lib/postgresql/data
    restart: always

  mymapp_redis:
    ports:
      - 8803:6379
    image: redis:latest
    restart: always
