// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag at
// 2019-07-18 15:19:41.5948336 +0800 CST m=+3.196182801

package docs

import (
	"bytes"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "license": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/config": {
            "get": {
                "description": "获取用户配置",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "config"
                ],
                "summary": "获取用户配置",
                "parameters": [
                    {
                        "type": "string",
                        "description": "With the bearer started JWT",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"Error\":\"Success\",\"Data\": object}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "301": {
                        "description": "{\"Error\":\"Re-login\",\"Data\": object}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "{\"Error\":\"error\",\"Data\": null}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "put": {
                "description": ".更改用户配置",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "config"
                ],
                "summary": ".更改用户配置",
                "parameters": [
                    {
                        "type": "string",
                        "description": "With the bearer started JWT",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "用户配置信息",
                        "name": "configuration",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/api.Configuration"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"Error\":\"Success\",\"Data\": object}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "301": {
                        "description": "{\"Error\":\"Re-login\",\"Data\": object}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "{\"Error\":\"error\",\"Data\": null}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/configState": {
            "get": {
                "description": ".获取状态配置",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "config"
                ],
                "summary": ".获取状态配置",
                "parameters": [
                    {
                        "type": "string",
                        "description": "With the bearer started JWT",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"Error\":\"Success\",\"Data\": object}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "301": {
                        "description": "{\"Error\":\"Re-login\",\"Data\": object}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "{\"Error\":\"error\",\"Data\": null}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "put": {
                "description": ".更改状态配置",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "config"
                ],
                "summary": ".更改状态配置",
                "parameters": [
                    {
                        "type": "string",
                        "description": "With the bearer started JWT",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "状态配置信息",
                        "name": "configState",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/api.ConfigState"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"Error\":\"Success\",\"Data\": object}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "301": {
                        "description": "{\"Error\":\"Re-login\",\"Data\": object}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "{\"Error\":\"error\",\"Data\": null}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/devicedata": {
            "get": {
                "description": "获取数据列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "devicedata"
                ],
                "summary": "获取数据列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "With the bearer started JWT",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "起始数",
                        "name": "offset",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "获取数",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "数据状态(自定义状态)",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "数据起始时间",
                        "name": "starttime",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "数据终止时间",
                        "name": "endtime",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "设备id",
                        "name": "id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"Error\":\"Success\",\"Data\": object}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "301": {
                        "description": "{\"Error\":\"Re-login\",\"Data\": object}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "{\"Error\":\"error\",\"Data\": null}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "description": "设备数据推送 -- 只接受管理员账号数据推送",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "devicedata"
                ],
                "summary": "设备数据推送",
                "parameters": [
                    {
                        "type": "string",
                        "description": "With the bearer started JWT",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "设备数据信息",
                        "name": "userInfo",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/api.DeviceInfos"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"Result\": object}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "301": {
                        "description": "{\"Error\":\"Re-login\",\"Data\": object}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "{\"Result\": null}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/devices": {
            "get": {
                "description": "获取设备列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "devices"
                ],
                "summary": "获取设备列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "With the bearer started JWT",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "起始数",
                        "name": "offset",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "获取数",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "设备状态 1启用 2禁用 3已过期",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "设备到期起始时间",
                        "name": "starttime",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "设备到期终止时间",
                        "name": "endtime",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "设备名",
                        "name": "name",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "群组id",
                        "name": "classid",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "用户id",
                        "name": "uid",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "设备id",
                        "name": "id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"Error\":\"Success\",\"Data\": object}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "301": {
                        "description": "{\"Error\":\"Re-login\",\"Data\": object}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "{\"Error\":\"error\",\"Data\": null}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "description": ".删除设备",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "devices"
                ],
                "summary": ".删除设备(仅管理员以上)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "With the bearer started JWT",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "设备ID",
                        "name": "devicesID",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/api.DevicesID"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"Error\":\"Success\",\"Data\": object}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "301": {
                        "description": "{\"Error\":\"Re-login\",\"Data\": object}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "{\"Error\":\"error\",\"Data\": null}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/devices/expire": {
            "put": {
                "description": ".更改设备过期时间",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "devices"
                ],
                "summary": ".更改设备过期时间(仅管理员以上)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "With the bearer started JWT",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "设备过期时间信息",
                        "name": "deviceExpire",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/api.DeviceExpire"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"Error\":\"Success\",\"Data\": object}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "301": {
                        "description": "{\"Error\":\"Re-login\",\"Data\": object}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "{\"Error\":\"error\",\"Data\": null}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/devices/status": {
            "put": {
                "description": "更改设备状态",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "devices"
                ],
                "summary": "更改设备状态(仅管理员以上)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "With the bearer started JWT",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "设备状态信息",
                        "name": "deviceStatus",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/api.DeviceStatus"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"Error\":\"Success\",\"Data\": object}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "301": {
                        "description": "{\"Error\":\"Re-login\",\"Data\": object}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "{\"Error\":\"error\",\"Data\": null}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/devices/user": {
            "put": {
                "description": ".更改设备所属权",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "devices"
                ],
                "summary": ".更改设备所属权(仅管理员以上)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "With the bearer started JWT",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "设备所属权信息",
                        "name": "devicesUser",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/api.DevicesUser"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"Error\":\"Success\",\"Data\": object}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "301": {
                        "description": "{\"Error\":\"Re-login\",\"Data\": object}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "{\"Error\":\"error\",\"Data\": null}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/fence": {
            "get": {
                "description": "获取用户围栏",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "fence"
                ],
                "summary": "获取用户围栏",
                "parameters": [
                    {
                        "type": "string",
                        "description": "With the bearer started JWT",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "用户ID",
                        "name": "id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"Error\":\"Success\",\"Data\": object}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "301": {
                        "description": "{\"Error\":\"Re-login\",\"Data\": object}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "{\"Error\":\"error\",\"Data\": null}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "description": ".设置用户围栏",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "fence"
                ],
                "summary": ".设置用户围栏",
                "parameters": [
                    {
                        "type": "string",
                        "description": "With the bearer started JWT",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "用户围栏信息",
                        "name": "fenceinfo",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/api.Fenceinfo"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"Error\":\"Success\",\"Data\": object}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "301": {
                        "description": "{\"Error\":\"Re-login\",\"Data\": object}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "{\"Error\":\"error\",\"Data\": null}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "description": ".删除用户围栏",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "fence"
                ],
                "summary": ".删除用户围栏",
                "parameters": [
                    {
                        "type": "string",
                        "description": "With the bearer started JWT",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "用户围栏信息",
                        "name": "fencetID",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/api.FencetID"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"Error\":\"Success\",\"Data\": object}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "301": {
                        "description": "{\"Error\":\"Re-login\",\"Data\": object}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "{\"Error\":\"error\",\"Data\": null}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/login": {
            "post": {
                "description": "账号登陆",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "login"
                ],
                "summary": "账号登陆",
                "parameters": [
                    {
                        "description": "登陆信息",
                        "name": "userInfo",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/api.LoginInfos"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"Error\":\"Success\",\"Data\": object}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "301": {
                        "description": "{\"Error\":\"Re-login\",\"Data\": object}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "{\"Error\":\"error\",\"Data\": null}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/login/code": {
            "get": {
                "description": "获取错误代码",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "login"
                ],
                "summary": "获取错误代码",
                "responses": {
                    "200": {
                        "description": "{\"Error\":\"Success\",\"Data\": object}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "301": {
                        "description": "{\"Error\":\"Re-login\",\"Data\": object}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "{\"Error\":\"error\",\"Data\": null}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/login/info": {
            "get": {
                "description": "获取登陆信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "login"
                ],
                "summary": "获取登陆信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "With the bearer started JWT",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"Error\":\"Success\",\"Data\": object}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "301": {
                        "description": "{\"Error\":\"Re-login\",\"Data\": object}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "{\"Error\":\"error\",\"Data\": null}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/login/logo": {
            "get": {
                "description": "获取背景图列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "login"
                ],
                "summary": "获取背景图列表",
                "responses": {
                    "200": {
                        "description": "{\"Error\":\"Success\",\"Data\": object}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "301": {
                        "description": "{\"Error\":\"Re-login\",\"Data\": object}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "{\"Error\":\"error\",\"Data\": null}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/login/register": {
            "put": {
                "description": "账号申请",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "login"
                ],
                "summary": "账号申请",
                "parameters": [
                    {
                        "description": "申请的用户信息",
                        "name": "userInfo",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/api.Registerinfo"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"Result\": object}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "301": {
                        "description": "{\"Error\":\"Re-login\",\"Data\": object}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "{\"Result\": null}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/login/register/name": {
            "get": {
                "description": "检测账号是否存在",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "login"
                ],
                "summary": "检测账号是否存在",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户名",
                        "name": "name",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"Error\":\"Success\",\"Data\": object}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "301": {
                        "description": "{\"Error\":\"Re-login\",\"Data\": object}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "{\"Error\":\"error\",\"Data\": null}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/upload": {
            "post": {
                "description": "图片上传",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "upload"
                ],
                "summary": "图片上传",
                "parameters": [
                    {
                        "type": "string",
                        "description": "JWT",
                        "name": "Authorization",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"Error\":\"Success\",\"Data\": object}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "301": {
                        "description": "{\"Error\":\"Re-login\",\"Data\": object}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "{\"Error\":\"error\",\"Data\": null}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/users": {
            "get": {
                "description": "获取用户列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "获取用户列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "With the bearer started JWT",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "起始数",
                        "name": "offset",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "获取数",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "用户状态 1启用 2禁用 3已过期",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "用户到期起始时间",
                        "name": "starttime",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "用户到期终止时间",
                        "name": "endtime",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "用户名",
                        "name": "name",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "群组id",
                        "name": "ownid",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "用户id",
                        "name": "id",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "用户级别",
                        "name": "permisson",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "VIP等级",
                        "name": "vip",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"Error\":\"Success\",\"Data\": object}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "301": {
                        "description": "{\"Error\":\"Re-login\",\"Data\": object}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "{\"Error\":\"error\",\"Data\": null}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "description": ".删除用户",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": ".删除用户(仅管理员以上)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "With the bearer started JWT",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "用户ID",
                        "name": "userDelID",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/api.UserDelID"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"Error\":\"Success\",\"Data\": object}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "301": {
                        "description": "{\"Error\":\"Re-login\",\"Data\": object}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "{\"Error\":\"error\",\"Data\": null}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/users/expire": {
            "put": {
                "description": ".更改用户过期时间",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": ".更改用户过期时间(仅管理员以上)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "With the bearer started JWT",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "用户过期时间信息",
                        "name": "userExpire",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/api.UserExpire"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"Error\":\"Success\",\"Data\": object}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "301": {
                        "description": "{\"Error\":\"Re-login\",\"Data\": object}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "{\"Error\":\"error\",\"Data\": null}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/users/info": {
            "put": {
                "description": ".更改用户信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": ".更改用户信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "With the bearer started JWT",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "用户信息",
                        "name": "Info",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/api.Info"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"Error\":\"Success\",\"Data\": object}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "301": {
                        "description": "{\"Error\":\"Re-login\",\"Data\": object}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "{\"Error\":\"error\",\"Data\": null}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/users/password": {
            "put": {
                "description": ".更改用户密码",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": ".更改用户密码",
                "parameters": [
                    {
                        "type": "string",
                        "description": "With the bearer started JWT",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "用户密码",
                        "name": "PasswordInfo",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/api.PasswordInfo"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"Error\":\"Success\",\"Data\": object}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "301": {
                        "description": "{\"Error\":\"Re-login\",\"Data\": object}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "{\"Error\":\"error\",\"Data\": null}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/users/status": {
            "put": {
                "description": "更改用户状态",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "更改用户状态(仅管理员以上)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "With the bearer started JWT",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "用户状态信息",
                        "name": "userStatus",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/api.UserStatus"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"Error\":\"Success\",\"Data\": object}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "301": {
                        "description": "{\"Error\":\"Re-login\",\"Data\": object}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "{\"Error\":\"error\",\"Data\": null}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/vip": {
            "get": {
                "description": "获取vip列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "vip"
                ],
                "summary": "获取vip列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "With the bearer started JWT",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"Error\":\"Success\",\"Data\": object}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "301": {
                        "description": "{\"Error\":\"Re-login\",\"Data\": object}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "{\"Error\":\"error\",\"Data\": null}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "put": {
                "description": "获取vip列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "vip"
                ],
                "summary": "获取vip列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "With the bearer started JWT",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "vip信息",
                        "name": "Permisson",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/api.Permisson"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"Error\":\"Success\",\"Data\": object}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "301": {
                        "description": "{\"Error\":\"Re-login\",\"Data\": object}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "{\"Error\":\"error\",\"Data\": null}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/ws": {
            "get": {
                "description": "websocket连接 /ws?maxiiot_user=token\u0026roomID=roomID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "websocket"
                ],
                "summary": "websocket连接 /ws?maxiiot_user=token\u0026roomID=roomID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "jwt",
                        "name": "Authorization",
                        "in": "query",
                        "required": true
                    }
                ]
            }
        }
    },
    "definitions": {
        "api.ConfigState": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "states": {
                    "type": "string"
                }
            }
        },
        "api.Configuration": {
            "type": "object",
            "properties": {
                "id": {
                    "description": "用户ID --不填",
                    "type": "integer"
                },
                "language": {
                    "description": "语言选择 1简体中文 2繁体中文 3英文 不更改不填或填0",
                    "type": "integer"
                },
                "message": {
                    "description": "消息推送开关 1开2关 不更改不填或填0",
                    "type": "integer"
                },
                "sound": {
                    "description": "声音开关 1开2关 不更改不填或填0",
                    "type": "integer"
                }
            }
        },
        "api.DeviceExpire": {
            "type": "object",
            "properties": {
                "expiredtime": {
                    "description": "过期时间",
                    "type": "integer"
                },
                "ids": {
                    "description": "设备ID",
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                }
            }
        },
        "api.DeviceInfos": {
            "type": "object",
            "properties": {
                "devEUI": {
                    "description": "设备UID",
                    "type": "string"
                },
                "info": {
                    "description": "展示在地图上的信息 json : {speend: 100, azimuth:20...} --",
                    "type": "object"
                },
                "latitude": {
                    "description": "纬度",
                    "type": "number"
                },
                "longitude": {
                    "description": "经度",
                    "type": "number"
                },
                "name": {
                    "description": "设备名称 -- 第一次有效",
                    "type": "string"
                },
                "state": {
                    "description": "状态 --自定义",
                    "type": "integer"
                },
                "times": {
                    "description": "时间 时间戳(秒)",
                    "type": "integer"
                }
            }
        },
        "api.DeviceStatus": {
            "type": "object",
            "properties": {
                "ids": {
                    "description": "设备ID",
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "status": {
                    "description": "状态",
                    "type": "integer"
                }
            }
        },
        "api.DevicesID": {
            "type": "object",
            "properties": {
                "ids": {
                    "description": "设备ID",
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                }
            }
        },
        "api.DevicesUser": {
            "type": "object",
            "properties": {
                "ids": {
                    "description": "设备ID",
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "uid": {
                    "description": "子用户ID",
                    "type": "integer"
                }
            }
        },
        "api.Fenceinfo": {
            "type": "object",
            "properties": {
                "info": {
                    "description": "围栏信息json  1: {Lat:21.32, Lng:113.21, radius: 123}  2:[{Lat:21.32, Lng:113.21}, {Lat:21.32, Lng:113.21}....]",
                    "type": "object"
                },
                "types": {
                    "description": "1 圆 2方",
                    "type": "integer"
                }
            }
        },
        "api.FencetID": {
            "type": "object",
            "properties": {
                "id": {
                    "description": "围栏ID  --传0则为删除自己的围栏",
                    "type": "integer"
                }
            }
        },
        "api.Info": {
            "type": "object",
            "properties": {
                "address": {
                    "description": "地址 不修改不传",
                    "type": "string"
                },
                "email": {
                    "description": "邮箱 不修改不传",
                    "type": "string"
                },
                "id": {
                    "description": "用户ID 修改自身不传",
                    "type": "integer"
                },
                "mobile": {
                    "description": "手机 不修改不传",
                    "type": "string"
                },
                "photo": {
                    "description": "头像  不修改不传",
                    "type": "string"
                }
            }
        },
        "api.LoginInfos": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "验证码",
                    "type": "string"
                },
                "name": {
                    "description": "登陆名",
                    "type": "string"
                },
                "password": {
                    "description": "密码 MD5加密(小写)",
                    "type": "string"
                }
            }
        },
        "api.PasswordInfo": {
            "type": "object",
            "properties": {
                "id": {
                    "description": "用户ID 修改自身不传",
                    "type": "integer"
                },
                "oldpassword": {
                    "description": "旧密码 MD5加密 修改下级用户不传",
                    "type": "string"
                },
                "password": {
                    "description": "新密码 MD5加密",
                    "type": "string"
                }
            }
        },
        "api.Permisson": {
            "type": "object",
            "properties": {
                "devices": {
                    "description": "设备数",
                    "type": "integer"
                },
                "fence": {
                    "description": "围栏权限 1启用 2禁止",
                    "type": "integer"
                },
                "fenceAlarm": {
                    "description": "围栏报警权限 1启用 2禁止",
                    "type": "integer"
                },
                "id": {
                    "description": "vipID",
                    "type": "integer"
                },
                "logo": {
                    "description": "定制LOGO权限 1启用 2禁止",
                    "type": "integer"
                },
                "orbit": {
                    "description": "轨迹权限 1启用 2禁止",
                    "type": "integer"
                },
                "real": {
                    "description": "实时数据权限 1启用 2禁止",
                    "type": "integer"
                },
                "users": {
                    "description": "子用户数",
                    "type": "integer"
                }
            }
        },
        "api.Registerinfo": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "验证码",
                    "type": "string"
                },
                "codeJWT": {
                    "description": "验证码标记",
                    "type": "string"
                },
                "email": {
                    "description": "邮箱",
                    "type": "string"
                },
                "mobile": {
                    "description": "手机号码",
                    "type": "string"
                },
                "name": {
                    "description": "账号",
                    "type": "string"
                },
                "password": {
                    "description": "密码 MD5加密(小写)",
                    "type": "string"
                }
            }
        },
        "api.UserDelID": {
            "type": "object",
            "properties": {
                "id": {
                    "description": "用户ID",
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                }
            }
        },
        "api.UserExpire": {
            "type": "object",
            "properties": {
                "expiredtime": {
                    "description": "过期时间",
                    "type": "integer"
                },
                "ids": {
                    "description": "用户ID",
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                }
            }
        },
        "api.UserStatus": {
            "type": "object",
            "properties": {
                "ids": {
                    "description": "用户ID",
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "status": {
                    "description": "状态",
                    "type": "integer"
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo swaggerInfo

type s struct{}

func (s *s) ReadDoc() string {
	t, err := template.New("swagger_info").Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, SwaggerInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
